### ISSUE TITLE
vf-banner will need to be a direct child of vf-body

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#112]
When changes to https://github.com/visual-framework/vf-core/pull/687 get merged in we would need to update the CSS for `vf-wp` and also remove the `vf-grid` surrounding the ContenHub `vf-banner` for the questionnaire.

**Comment by khawkins98** [comment]
The above has been merged and addressed: https://wwwdev.ebi.ac.uk/about/teams/web-development/
