### ISSUE TITLE
Intranet: Keywords for search are not picked up

### ISSUE THREAD

**Issue by spivass81** [visual-framework/vf-wp#1142]
@szymon, seems that the keywords we have implemented for search on the intranet are not working at the moment or at least not working for the specific use case below:

I have added the keyword "its" to the IT Services page for the intranet, no hits though:

https://www.embl.org/internal-information/search/its?post_type=any&q=its&#stq=its&stp=1

Here is the  link to the IT Services page:

https://www.embl.org/internal-information/it-services/

Could you take a look once you'll get a chance?

**Comment by kasprzyk-sz** [comment]
The keywords work fine in general, the 'its' term may be too short. Anyway, I added 'its' as a synonym of 'IT Services' and it seems to be working fine.

**Comment by spivass81** [comment]
Ahhh, had forgotten about these!! Great, working smooth, closing!!
