### ISSUE TITLE
Security: Disable xmlrpc from all wordpress setup

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#1144]
Based on security team feedback we need to disable xmlrpc links which are default enabled by WordPress. This will avoid any brute or DDos attacks on the site.

We need to add following code to main vf-wp function.php so that it will get applied to all websites.

`
add_filter('xmlrpc_enabled', '__return_false');
`

**Comment by kasprzyk-sz** [comment]
added in [89cd0dc](https://github.com/visual-framework/vf-wp/commit/89cd0dceeae98b7c16f353d97bdf91adf709763c)
