### ISSUE TITLE
Based on VF core release 2.5.8 we need to change h2 of vf-hero__heading to h1

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#1157]
Based on VF core release 2.5.8 where we have addressed accessibility issue with hero heading by changing h2 to h1, similarly we need to update WordPress block of Hero to accommodate this change.

Background - https://github.com/orgs/visual-framework/projects/7

https://github.com/visual-framework/vf-core/pull/1769

**Comment by kasprzyk-sz** [comment]
Done in https://github.com/visual-framework/vf-wp/commit/218d9c29e6cc01cdf96d9f466f78b3ae2308ffa2

**Comment by sandykadam** [comment]
This fix is for all page primary heading.
