### ISSUE TITLE
Conditionality display heading for VF-Intro block to fix accessibility issues

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#1158]
Recently all EBI pages are created from EditorHub, we have page called "[Our impact](https://www.ebi.ac.uk/about/our-impact)" in about section. On this page we have accessibility error for the VF-Intro block, as per this page content there is no need for title to be added in intro block but page still renders `<h1>` tag with empty, thus WAVE give accessibility error. Please find screenshot attached.

Issue reported in https://www.ebi.ac.uk/panda/jira/browse/ECWR-146

Following changes need to be done to the block-

- [ ] Change heading tag h1 to h2 for the title
- [ ] Display this tag only if there is heading/title added

![Screenshot 2022-08-23 at 16 05 03](https://user-images.githubusercontent.com/1227241/186196217-b23aea89-66be-4b8e-9711-2cd9a369a9c9.png)

**Comment by kasprzyk-sz** [comment]
Done in https://github.com/visual-framework/vf-wp/commit/b235df7f5e04f6d1ffd8299528b681038718d4a0

**Comment by sandykadam** [comment]
Thanks @kasprzyk-sz is this updated in any tag?

**Comment by kasprzyk-sz** [comment]
Yes, that was included in v2.1.6

**Comment by sandykadam** [comment]
This is fixed and deployed in editorhub, so we can close this.
