### ISSUE TITLE
Accessibility contrast color fixes for vf-social blocks

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#1201]
VF release for vf-social blocks (https://github.com/visual-framework/vf-core/pull/1808) changes needs to be added in WP block.

**Comment by nikiforosk** [comment]
The vf-social blocks in the Meet our people profiles (e.g. about [John Lees](https://www.ebi.ac.uk/about/jobs/career-profiles/john-lees-group-leader)) have been updated and the previous contrast issues have been resolved so I'm closing this issue.
