### ISSUE TITLE
Update vf-button markup in wordpress block and static pages

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-wp#1208]
The `vf-button` block in WP outputs the following HTML:

`<a href="https://stable.visual-framework.dev/wordpress/page-6/" class="vf-button vf-button--primary">Page 6</a>`

The goal is to update it to:

`<a href="https://stable.visual-framework.dev/wordpress/page-6" target="_blank">
   <button class="vf-button vf-button--primary">Page 6</button>
  </a>`

**Comment by nikiforosk** [comment]
@kasprzyk-sz can you add a page that uses this button for me to review once the changes are done?

**Comment by nikiforosk** [comment]
The WP vf-buttons on [the International applicants page](https://www.ebi.ac.uk/about/jobs/international-applicants) have been updated and they work as expected so I'm closing this issue.
