### ISSUE TITLE
Section header of WP container is not showing

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-wp#1209]
We noticed this when I updated the card containers on this page:
https://www.embl.org/editorhub/meet-our-people/

It looks like that changing the background from the default white to lightest gray and then back to white (and then updating the page) resolves this issue.

**Comment by nikiforosk** [comment]
The headers are back in [the Life at EBI page](https://www.ebi.ac.uk/about/jobs/life-at-embl-ebi) and [the corresponding page in the editor hub](https://www.embl.org/editorhub/life-at-embl-ebi/) so I'm closing this issue.
