### ISSUE TITLE
Hidden section header in WP shouldn't be a link 

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-wp#1236]
> Sorry for coming late to this. In WordPress block it depends what kind of `section header` variant the user selects.
> 
> ![Image](https://user-images.githubusercontent.com/54020899/223959894-c6fda87f-67c9-4013-9ad4-8f560c620866.png)
> 
> By default, however, only the `<h2>` tag is outputed.

I had a quick look at the WordPress editor and I noticed that I can hide a `section header` that is a link:

![Screenshot 2023-03-16 at 09 50 24](https://user-images.githubusercontent.com/20280139/225580506-7a46217e-a99e-43e5-acbb-105b4099f097.png)

Ideally, we'd like the "Show header" option to be available only for the section headers that are **not** links. 

_Originally posted by @nikiforosk in https://github.com/visual-framework/vf-core/issues/1884#issuecomment-1471638659_

**Comment by sandykadam** [comment]
Lets close this, as it will be duplicated in VF-WP https://github.com/visual-framework/vf-wp/issues/1236

**Comment by nikiforosk** [comment]
> Lets close this, as it will be duplicated in VF-WP #1236

I think we are commenting to VF-WP #1236 now?

**Comment by nikiforosk** [comment]
How about subheadings?
