### ISSUE TITLE
Hide the default "Quote", "Pullquote" and legacy VF blockquote blocks in WP 

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-wp#1237]
During [our discussion with the comms team](https://docs.google.com/document/d/1AEL4XU2UM7Dz03DVt21q6aIAmnB4ENAh4IOksN4GBJQ/edit#heading=h.am2vybcg3sol) about [vf-blockquote](https://stable.visual-framework.dev/components/vf-blockquote/), we agreed to hide: 
- [ ] the default Quote block in WordPress 
- [ ] the Pullquote block in WordPress 
- [ ] the legacy VF Blockquote block in WordPress

so that they don't select those instead of vf-blockquote.

![Screenshot 2023-03-28 at 11 03 50 copy](https://user-images.githubusercontent.com/20280139/229809133-0f708478-d81b-4b7f-8019-33619bc919f2.png)

We want to investigate:
- [ ] Is this feasible?
- [ ] What will happen to the various articles that use these components e.g. https://www.ebi.ac.uk/about/news/perspectives/alphafold-using-open-data-and-ai-to-discover-the-3d-protein-universe/

NB: @Adedoyinebi will explore ways to improve VF blockquote in [vf-core 1195](https://github.com/visual-framework/vf-core/issues/1915).

**Comment by geetikamalhotra** [comment]
@nikiforosk @kasprzyk-sz , Please may I know if the VF blockquote component works as a Pull quote or a block quote? As per my understanding the difference between the two is - "The main purpose of a blockquote is to separate a large section of text — quoted from an outside source — that is relevant to the source material at hand. A pull quote is a section of the article pulled out of its context and **repeated to give either emphasis**, or to aid the reader in scanning the article." I feel both are important and as part of any design system functionality both should be available for use.

**Comment by nikiforosk** [comment]
@geetikamalhotra Our understanding from the discussion with Comms is that they use blockquotes. They weren't actually aware of the difference between blockquote and pullquote (which might be why the VF only has a blockquote component). They noted that providing fewer options is better at this point as a single blockquote component is more likely to be used consistently.

Please note that we track the relevant design work in this issue: https://github.com/visual-framework/vf-core/issues/1915

> @nikiforosk @kasprzyk-sz , Please may I know if the VF blockquote component works as a Pull quote or a block quote? As per my understanding the difference between the two is - "The main purpose of a blockquote is to separate a large section of text — quoted from an outside source — that is relevant to the source material at hand. A pull quote is a section of the article pulled out of its context and **repeated to give either emphasis**, or to aid the reader in scanning the article." I feel both are important and as part of any design system functionality both should be available for use.
