### ISSUE TITLE
remove embl-grid wrapping vf-breadcrumbs 

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#13]
We'd need to change the `grid-column` for `vf-breadcrumbs` for this not to break.

`embl-grid` adds vertical spacing which looks horrid for simple components like this, and as with the groups, like it seems the dashboard - `vf-body` is the parent so it could grab the grid from that.

Also - if `vf-core` has the grid changes making things `max-width` and `margin: 0 auto` it would tighten this up a little too

So, there's options.

**Comment by khawkins98** [comment]
I think this has been done in #14.
