### ISSUE TITLE
ENHANCEMENT - "No results" behaviour for blocks

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#140]
When a query to the contentHub returns no results, it would be nice to have a "No results behaviour".

My initial thought:

### No results behaviour

Options:

- Default (as specified in the plugin)
    - Might be: "No jobs could be found at this time."
- Hide the widget 
- Use custom text

**Comment by dbushell** [comment]
Some progress on this for recent plugins (e.g. ["Person" block](https://github.com/visual-framework/vf-wp/tree/master/wp-content/plugins/vf-members-block/vf-person)):

In the Gutenberg editor — a new Person block:

![vf-person-notice](https://user-images.githubusercontent.com/998922/81155867-eb025b80-8f74-11ea-9e24-68db17a72633.png)

And if the Content Hub returns nothing:

![vf-person-error](https://user-images.githubusercontent.com/998922/81155873-ec338880-8f74-11ea-8f6d-590bb51eb482.png)

On the front-end nothing is rendered until the Content Hub can return valid html.

For older plugins on the front-end the Cache plugin falls back to:
```html
<link rel="import" href="" data-target="self" data-embl-js-content-hub-loader>
```

Just on the of chance the Content Hub API was inaccessible. I forget exactly the flow there.

What would be very helpful is if the Content Hub provide error messages so we can differentiate between access errors and no results. Is that possible right now?

**Comment by dbushell** [comment]
More progress here in PR #285 - all blocks will be ACF in future making the templating easier with `$is_preview`.
