### ISSUE TITLE
CHORE - Petrol/green options can be removed

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#141]
The code that allowed the header to be set as EMBL Green or EBI Petrol I believe is no longer used (or needed) with the new vf-masthead, at least for the vf-wp-group child theme.

https://github.com/visual-framework/vf-wp/blob/c675e1b2f81ecb585653b273941d83b4a044d0f6/wp-content/themes/vf-wp-groups/functions/groups-customize.php#L89-L94

https://github.com/visual-framework/vf-wp/blob/c675e1b2f81ecb585653b273941d83b4a044d0f6/wp-content/themes/vf-wp-groups/functions/groups-customize.php#L157-L171

If so, we should remove the configuration option and code. 

---

This relates to https://github.com/visual-framework/vf-core/issues/758 and the vf-masthead (sort of) no longer supporting colourisation.

**Comment by khawkins98** [comment]
Filed as  a bug because the option doesn't do what it says in the interface.

**Comment by sturobson** [comment]
aside: as the green is the brand colour for 'one embl' we shouldn't be having petrol at all anyway now?

**Comment by khawkins98** [comment]
> aside: as the green is the brand colour for 'one embl' we shouldn't be having petrol at all anyway now?

hahahahaahahahahahhhhah ha ha ...

**Comment by khawkins98** [comment]
But, seriously, yes that's true. But it's only ok if you first allow sites to use petrol. 

Fortunately the new background is white so it sidesteps a lot of it. 

Until someone asks about the hero background. Hopefully they won't -- but that would tie into a wider theming conversation.
