### ISSUE TITLE
logo missing?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#171]
I know things have changed for the `embl-logo` component. I think this needs updating in the group pages as there is now logo appearing at all.

Checked these sites to make sure it's not a 'one-off':

- http://dev.beta.embl.org/groups/bernabeu
- http://dev.beta.embl.org/groups/ebisuya
- http://dev.beta.embl.org/groups/ellenberg
- http://dev.beta.embl.org/groups/ephrussi
- http://dev.beta.embl.org/groups/eustermann
- http://dev.beta.embl.org/groups/galej
- http://dev.beta.embl.org/groups/garcia-alai
- http://dev.beta.embl.org/groups/gibson
- http://dev.beta.embl.org/groups/haase
- http://dev.beta.embl.org/groups/hackett
- http://dev.beta.embl.org/groups/hiiragi
- http://dev.beta.embl.org/groups/koehler
- http://dev.beta.embl.org/groups/korbel
- http://dev.beta.embl.org/groups/krebs
- http://dev.beta.embl.org/groups/lancrin
- http://dev.beta.embl.org/groups/loew
- http://dev.beta.embl.org/groups/marquez
- http://dev.beta.embl.org/groups/ries
- http://dev.beta.embl.org/groups/steinmetz
- http://dev.beta.embl.org/groups/zaugg
- https://dev.beta.embl.org/groups/ellenberg/
- https://dev.beta.embl.org/groups/gibson/
- https://dev.beta.embl.org/groups/koehler/
- https://dev.beta.embl.org/groups/loew/
- https://dev.beta.embl.org/groups/ries/
- https://dev.beta.embl.org/groups/zaugg/
- https://dev.beta.embl.org/groups/eustermann/

Unless I'm missing something?

**Comment by khawkins98** [comment]
Updating to the latest components did the job -- there was that release of embl-logo that wasn't showing the logo when it was inside a flex container.

**Comment by khawkins98** [comment]
Think this one's sorted.
