### ISSUE TITLE
Chore: wire up new embl-notifications

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#182]
Should utilise the contentHub for notifications and disable the hardcoded single message.

**Comment by khawkins98** [comment]
Notifications were added in https://github.com/visual-framework/vf-wp/commit/35cdccc692eae230bef137ba3f0eb89bf56f2e29

We should disable or remove the `vf-beta-container` plugin from all sites.

**Comment by dbushell** [comment]
The `vf-beta-container` plugin has been "deprecated" (commit: https://github.com/visual-framework/vf-wp/commit/b8eebd4ea9e597ea16cf7aa5d3f1be2b2f8b09b4). I've bumped the version - files still exist but do nothing. It will be safe to delete the plugin directory when:

- [ ] templates aren't blindly hard-coding (e.g. without `if (class_exists('VF_Beta'))`)
- [ ] setup/deploy scripts ignore if missing

In theory I could upgrade the core `vf-wp` plugin to automatically deactivated a list of deprecated plugins. Although WordPress does that anyway if it's missing – should think about various scenarios more...
