### ISSUE TITLE
CSS: Remove guttenberg button styling

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#184]
By default WP is attaching some styling that clashes hard with VF styles; see: https://www.embl.org/news/lab-matters/corona-updates/

Here `.wp-block-button` is resulting in:

![image](https://user-images.githubusercontent.com/928100/76978855-842ed180-6937-11ea-8c1f-d883a7b765fa.png)

Here's one possible approach to resolve: https://github.com/WordPress/gutenberg/issues/11338#issuecomment-441451465

> Removing works fine for me with the following example:
> 
> ```js
> wp.domReady( () => {
> 	wp.blocks.unregisterBlockStyle( 'core/quote', 'default' );
> 	wp.blocks.unregisterBlockStyle( 'core/quote', 'large' );
> 
> 	wp.blocks.unregisterBlockStyle( 'core/button', 'default' );
> 	wp.blocks.unregisterBlockStyle( 'core/button', 'outline' );
> 	wp.blocks.unregisterBlockStyle( 'core/button', 'squared' );
> } );
> ```
> 
> This script is enqueued via `wp_enqueue_script( 'gutenberg-testing', plugins_url( 'editor.js', __FILE__ ), array( 'wp-blocks', 'wp-dom' ), time(), true );`
>

**Comment by sturobson** [comment]
It would be great if we had WordPress not creating and adding any classes to the markup. 

I can't see a 'catch all' in any functions.php file yet - but there must be something close.

**Comment by khawkins98** [comment]
There must be a list someones made of all the block, so you can use the above approach to just deregister all the things.

**Comment by khawkins98** [comment]
Sorted by #187
