### ISSUE TITLE
Events plugin stage 2 requirments

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#228]
David has made a foundational events plugin in #225 -- it will allow EBI Devs to begin integrating into the contentHub, but to complete the work we'll need some more fields.

Those fields will largely need to reflect the ones in the [contentHub `event` content type](https://content.embl.org/admin/structure/types/manage/event/fields):

field name | machine name | type
--- | --- | --- 
Additional Info | field_event_additional_info | Text (formatted, long, with summary)
Canceled | field_event_canceled | List (integer)
Closing date | field_event_registration_closing | Date
Closing date | field_event_submission_closing | Date
Description | body | Text (formatted, long, with summary)
EMBL.org term: what | field_embl_org_term_what | Entity reference
EMBL.org term: where | field_embl_org_term_where | Entity reference
EMBL.org term: who | field_embl_org_term_who | Entity reference
End date | field_event_end_date_time | Date
Feeds item | feeds_item | Feed
Location | field_event_location | Entity reference
More Information link | field_event_more_information | Link
Opening date | field_event_registration_opening | Date
Opening date | field_event_submission_opening | Date
Registration Fee | field_event_registration_fe | Text (plain)
Registration Link | field_event_registration_link | Link
Start date | field_event_start_date_time | Date
Tags | field_tags | Entity reference
Type | field_event_type | List (text)
Unique Identifier | field_event_unique_identifier | Text (plain)
Venue | field_event_venue | Text (plain) |  

And here's what it looks like with content: 

![image](https://user-images.githubusercontent.com/928100/79426201-17086d80-7fc3-11ea-9d68-666f6e590798.png)

Not all of these are strictly required, but this is a full list for informational needs.

**Comment by dbushell** [comment]
I'll remove the EMBL taxonomy for general event tagging. We can use a "Taxonomy" field type in ACF for specific fields (EMBL Taxonomy plugin must be enabled to see).

I've already added `Start Date` `End Date` and `Location`.

The `Description` field should use the normal `post_content`. `Title` matches `post_title` of course.

Maybe `Type` can use a custom post taxonomy rather than an ACF field – this would allow more useful WP features and templating options in future.

**Comment by khawkins98** [comment]
> I'll remove the EMBL taxonomy for general event tagging. We can use a "Taxonomy" field type in ACF for specific fields (EMBL Taxonomy plugin must be enabled to see).

We'll still want to be able to tag Events with the EMBL taxonomy (it's `field_embl_org_term_what` `field_embl_org_term_where` `field_embl_org_term_who` in the above), and then misc free terms too. 

On the dates, did those have times? Glancing at the PR it looked like just the date? 

All the rest sounds grand.

**Comment by dbushell** [comment]
> and then misc free terms too

Cool I'll leave the tags in!

> On the dates, did those have times? Glancing at the PR it looked like just the date?

Just dates. I suggest we add separate field for start/end time. I absoutely loathe combine date/time pickers. We can always merge these in the REST API or somewhere.

**Comment by khawkins98** [comment]
☝️ good stuff.

**Comment by dbushell** [comment]
Events plugin running locally in the `vf-wp-news` theme (following a few upgrades)

![Screenshot 2020-04-17 at 13 59 17](https://user-images.githubusercontent.com/998922/79572123-ee0fd780-80ab-11ea-9978-95e6f1eb6cdb.png)

it should be noted how barebones the default templates are. They can be overridden with theme-specific ones.
