### ISSUE TITLE
Regression: EBI header and footer not present in new template

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#230]
As spotted by @sandykadam: The new template defaults to the EMBL header+footer, which means EBI sites now get the wrong header+footer:

![image](https://user-images.githubusercontent.com/928100/79558487-830ed280-80a4-11ea-9c59-9e894f81cbb6.png)

There are number of possible approaches:

1. have the template referance all 4: EMBL header+footer and EBI header+footer and then if a plugin is disable it just wouldn’t show
2. add an option to change the “default” one the deployment script would just have to edit the default post
3. others?

Probably will have to wait until @dbushell is back on the week of the 27th

**Comment by dbushell** [comment]
So right now the plugin assumes one "default" template. Alternates can be created and assigned per-page like normal WP templates.

The default template is currently hard-coded in the plugin and inserted when the plugin actives (if it doesn't exist):

```html
<!-- wp:vf/container-global-header /-->

<!-- wp:vf/container-page-template /-->

<!-- wp:vf/container-global-footer /-->
```

The EBI version would be:

```html
<!-- wp:vf/container-ebi-global-header /-->

<!-- wp:vf/container-page-template /-->

<!-- wp:vf/container-ebi-global-footer /-->
```

Referencing all 4 and only activating 2 plugins would work. Feels a bit hacky!

* The plugin could insert two templates and allow the default to be selected (via a global option, manually, or programmatic on deploy).

The plugin inserts no templates; the deploy script must insert a "default".

* I think this would be most user-friendly.

After the deploy script installs the theme and plugins it could always simply edit all of the `vf_template` post and insert/amend as needed.

**Comment by sandykadam** [comment]
Let me know if there is any update needed on VF bootstrap script - https://gitlab.ebi.ac.uk/ebiwd/vf-wp-microsites/blob/master/bin/vf_bootstrap

**Comment by dbushell** [comment]
Quick correction for reference – the Groups sites default template is:

```html
<!-- wp:vf/container-global-header /-->

<!-- wp:vf/container-breadcrumbs /-->

<!-- wp:vf/container-wp-groups-header /-->

<!-- wp:vf/container-page-template /-->

<!-- wp:vf/container-embl-news /-->

<!-- wp:vf/container-global-footer /-->
```

**Comment by dbushell** [comment]
As the theme is used for non-group sites we should probably update this with the bootstrap script.

After theme and plugins are installed/activated:

1. Edit or create the WP post:
 * `post_type` = `vf_template`
 * `post_name` = `default`
 * `post_title` = "Default" or "Groups (default)" or similar

2. Set the `post_content` to the tempate https://github.com/visual-framework/vf-wp/issues/230#issuecomment-615179044

is that possible @sandykadam?

**Comment by dbushell** [comment]
Also the `options_vf_containers` options are no longer used (replaced by these templates). So they can be ignored or removed from the scripts (like 12 lines or so).

**Comment by dbushell** [comment]
I've updated the documentation @sandykadam 

https://github.com/visual-framework/vf-wp/blob/master/docs/wordpress.md#configure-the-default-template

let me know if it needs any clarification

**Comment by sandykadam** [comment]
Done, updated changes in deployment script

**Comment by khawkins98** [comment]
This is now done:

https://wwwdev.ebi.ac.uk/about/teams/training/

![image](https://user-images.githubusercontent.com/928100/80463538-abb28a00-8938-11ea-8149-8c4e5605d06b.png)

There are still some opportunities to improve the mechanism for this, @dbushell is thinking on it
