### ISSUE TITLE
cleanup vf-wp-news theme and ensure it works with new templates

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#231]
Need to check if the `vf-wp-news` theme works with the new templating system.

Also remove unused files (e.g. `/functions/` directory).

**Comment by dbushell** [comment]
working in this branch:
https://github.com/visual-framework/vf-wp/tree/fix/issue-231

@kasprzyk-sz would you be able to add an `acf-json` folder to the theme and export all the groups? I'll add a filter to load the JSON files.

**Comment by kasprzyk-sz** [comment]
Yep, will do that!
