### ISSUE TITLE
vf-text and it's variants are a last resort for components

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#233]
I was going through some recent code changes and noticed 

https://github.com/visual-framework/vf-wp/compare/v0.0.37...master#diff-a0b59d636fa79df20ff152ebec396c7eR119

with lots of `vf-text vf-text-heading--` shouldn't these options be whatever the component is? A 'single event'? Also noticed `main` in there… that's the only `<main>` on the page, right?

**Comment by kasprzyk-sz** [comment]
You're right. It's all wrapped in `vf-content` so no point of having extra classes. I'll clean it up.

**Comment by dbushell** [comment]
Original link in Stu's comment is broken, but sounds like you've got this @kasprzyk-sz?

**Comment by kasprzyk-sz** [comment]
Yes, I removed them, but it's on a branch that hasn't been merged yet.

**Comment by kasprzyk-sz** [comment]
vf-text removed in #323
