### ISSUE TITLE
ENHANCEMENT - Allow querying for specific persons, teams

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#234]
There's a need to be able to do a bit more with people querying:

**1. Query by custom team**

Probably an easy-ish enhancement to the existing `vf-members` logic to not query for the current team, but to "show me all the members of Web Development"

**2. Show a specific person(s)**

This might need to be a new Gutenberg block to show `vf-person` and query for a specific person by `name` or `UUID` ... "show me Ken Hawkins as `vf-summary--large` or `--medium`"

**Comment by dbushell** [comment]
Looks like an easy enhancement. Hey @khawkins98  do you have example Content Hub queries and parameters for both so I can understand what UI to add.

**Comment by khawkins98** [comment]
Some samples:

- Show a specific person by name:
  https://www.embl.org/api/v1/pattern.html?pattern=vf-summary-profile-s&filter-content-type=person&filter-field-contains[field_person_full_name]=Ken%20Hawkins&limit=1&source=contenthub
- Or a person by EMBL CP-ID
  https://www.embl.org/api/v1/pattern.html?pattern=vf-summary-profile-s&filter-content-type=person&filter-field-contains[field_person_embl_id]=CP-60022294&limit=1&source=contenthub
- Show a specific team by name
  https://content.embl.org/api/v1/pattern.html?filter-content-type=person&filter-field-contains%5Bfield_person_positions.entity.field_position_team.entity.title%5D=Communications&filter-field-value-not%5Bfield_person_positions.entity.field_position_membership%5D=leader&filter-fields-empty=field_person_visible_internally&limit=20&pattern=vf-summary-profile-l&sort-field-value%5Bchanged%5D=DESC





More sample queries: https://docs.google.com/spreadsheets/d/1ThNJn7TSQ1nlmjRONhyHU4orXx2cC97XGejoOphP5QI/edit#gid=0

**Comment by dbushell** [comment]
![vf-person-block](https://user-images.githubusercontent.com/998922/80584476-4080ba80-8a01-11ea-870c-da8a8a6afcc8.png)

@khawkins98 this look good for single person block? any other variables? Search by is "Full Name" or "EMBL CP-ID".

**Comment by khawkins98** [comment]
Nice.

These are the four variants in the contentHub:

- https://gitlab.ebi.ac.uk/emblorg/drupal-sites/content-hub/tree/develop/dist/modules/custom/content_hub_api/templates
  - vf-summary-profile-l
  - vf-summary-profile-r
  - vf-summary-profile-s
  - vf-summary-profile

**Comment by khawkins98** [comment]
☝️ Not sure if you've got those in already, but otherwise good to go from my view.

**Comment by dbushell** [comment]
I've got "Small", "Regular", "Large", what is the last one without a suffix?

**Comment by khawkins98** [comment]
Everything in one? 😆 

Seem the non-suffixed one also list the team name. I'm not clear on the historical reason for this. Could be that `vf-summary-profile` existed before the `vf-summary-profile-l` `-r` `-s` variants. 

- vf-summary-profile-l https://www.embl.org/api/v1/pattern.html?pattern=vf-summary-profile-l&filter-content-type=person&filter-field-contains%5Bfield_person_full_name%5D=Ken%20Hawkins&limit=1&source=contenthub
- vf-summary-profile https://www.embl.org/api/v1/pattern.html?pattern=vf-summary-profile&filter-content-type=person&filter-field-contains%5Bfield_person_full_name%5D=Ken%20Hawkins&limit=1&source=contenthub

**Comment by dbushell** [comment]
I'll call it "Full" for now.

**Comment by dbushell** [comment]
![team-members](https://user-images.githubusercontent.com/998922/80610109-78e7bf00-8a28-11ea-9bc9-2c803aa328d6.png)

Work in progress expanding the `vf-members` plugin options.
