### ISSUE TITLE
Group homepage "About" description box overlaps on cookie banner on small screens

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#236]
Group homepage "About" description box which we show on hero banner overlaps on cookie banner on small screens when we scroll down if we don't close cookie banner.
![Screenshot 2020-04-21 at 13 54 46](https://user-images.githubusercontent.com/1227241/79868745-46aae180-83d8-11ea-80fc-357c7533bab5.png)

**Comment by sturobson** [comment]
This will be something to fix in `vf-core` as it’ll probably effect any site (not just WP) that uses these two things.

I’ll raise an issue there and link it to this so progress can be tracked.

**Comment by khawkins98** [comment]
There was a similar issue back in https://github.com/visual-framework/vf-core/issues/19
