### ISSUE TITLE
BUG - IE11 JavaScript 'crashes' when developer tools are open

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#238]
problem:

When testing things in IE11 on a refresh developer tools would 'pause' because it has no idea what a promise is.

potential fix:

I think `vf-wp` needs to include https://www.npmjs.com/package/@visual-framework/vf-polyfill-js in it's `package.json`

**Comment by dbushell** [comment]
Didn't know IE11 was support! does the VF work with all the grid etc?

All the CSS/JS comes from `vf-core` wouldn't this be added as a dependency there? I'm not too caught up on how the gulp tasks and assets work in the WP repo maybe @khawkins98 can advise.

**Comment by khawkins98** [comment]
The ie11 JS support comes in two parts:

1. Everything is transpiled to ES5 (vf-core is already doing this for vf-wp)
2. The vf-polyfill-js that Stu mentioned above

For vf-pollyfill-js to work this HTML needs to be inserted on the page:

`<script nomodule src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>`

That JS isn't added to the main `scripts.js` as:

> serve the JS to only the browsers that need it by using the nomodule attribute in script tags; as MDN web docs puts it: "in effect, this can be used to serve fallback scripts to older browsers that do not support modular JavaScript code".

So, tl;dr: if we just add the line of JS to the template before the VF's scripts.js, we'll be all set.

**Comment by dbushell** [comment]
Would it be possible to add an `async` to that script tag or does it need to load before `scripts.js`? I'm not keen on external resources halting the page load.

**Comment by khawkins98** [comment]
It needs to load first, but as it uses `nomodule` it will be ignored by all but IE11 (where performance is terrible anyways).

**Comment by dbushell** [comment]
Added the polyfill to the `<head>` above all scripts.

A quick test shows it's loading in IE11. I didn't experience any crashes either way, but assuming this is fixed now?

**Comment by khawkins98** [comment]
- [x] has more javascript
