### ISSUE TITLE
Two different cookie banners displayed on group sites

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#239]
If you try to access https://wwwdev.embl.org/groups/dummy-embl-group/ in incognito browser, you will see cookie banner with green button, once you click on it you will get one more cookie banner with regular text. Please find attached screenshots.

![Screenshot 2020-04-24 at 10 39 45](https://user-images.githubusercontent.com/1227241/80198705-63355c80-8618-11ea-8b0a-304d1c7715dc.png)
![Screenshot 2020-04-24 at 10 39 54](https://user-images.githubusercontent.com/1227241/80198712-64ff2000-8618-11ea-9802-dbb3b85339da.png)

**Comment by dbushell** [comment]
Any idea which script is inserting these @khawkins98? I don't think there is anything in this repo we can change to fix this.

**Comment by khawkins98** [comment]
The EBI plugins are active on this EMBL.org site, so this would be expected. 

![image](https://user-images.githubusercontent.com/928100/81154072-d5486280-8f83-11ea-8484-f333c868dc44.png)

Obviously that's a mistake, so I'm disabling them. Should clear it up.

**Comment by khawkins98** [comment]
I'm not sure why the EBI plugins would have been activated on an EMBL site ... @sandykadam 
deployment config issue, or just a simple accident?

**Comment by sandykadam** [comment]
Ohh ok, we use to enable all plugins irrespective of site so we could use for setting up container as per initial framework setup, I think now its changed with after v39 changes see #230.

**Comment by sandykadam** [comment]
This is now sorted in deployment script as well, so we can close.
