### ISSUE TITLE
DISCOVERY - Configure a group site and note rough edges

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#241]
I've asked Sandeep to reset the dummy sites to their default configurations:

- https://wwwdev.ebi.ac.uk/about/teams/dummy-ebi-group/
- https://wwwdev.embl.org/groups/dummy-embl-group/

On Tuesday we should all go through the site configuration as a "group admin" and note any rough edges, i.e.:

- "as a group admin I can't change the way publications are sorted"

This will help form the basis of work for this sprint and likely future ones and EDR+contentHub work.

**Comment by filipe-dias** [comment]
From this walkthrough, some issues came up:
- Login with `wp-login.php`, no `?normal`, leads to error page:
![login](https://user-images.githubusercontent.com/46531832/80474894-f8e62a00-893f-11ea-9c6a-5fe1aa083572.png)
- figure and caption layout issues - class handling?
- good to have a vf-banner for some noteworthy titles/links, like ERC Investigator
- publications list is not working - #248 
- main menu on mobile presents some challenges
- set hero to show only on home page

**Comment by khawkins98** [comment]
Let's repeat this exercise on Tuesday (5th)
