### ISSUE TITLE
ENHANCEMENT - Blog post features

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#242]
I cloned a blog post from the old EMBL Blogs site to the Communications microsite:

- https://blogs.embl.org/communications/2020/01/17/embl-org-from-so-simple-a-beginning/
- https://wwwdev.embl.org/groups/communications/blog/2020/01/embl-org-from-so-simple-a-beginning/

A few things that came up:

- Featured image? Would be good to show this on the blog index and push to contentHub 
- The author doesn't show on the actual post
- Local WP site tags don't show 
- Would also be good to have a EMBL.org tags show (who/what/where) but we don't have global EMBL.org topic pages yet

Related to #241

**Comment by kasprzyk-sz** [comment]
Should the blog post have the same/similar look as on news site?

**Comment by khawkins98** [comment]
I will get Mark's reference designs for the group and news post. and we can see if there are substantive differences.

**Comment by kasprzyk-sz** [comment]
I went through Mark's designs in Abstract but didn't find anything. Here is a very basic layout with a sidebar:
![Screenshot 2020-04-29 at 07 23 23](https://user-images.githubusercontent.com/54020899/80563342-1ae8b680-89eb-11ea-8d7b-d98daedf574f.png)

**Comment by khawkins98** [comment]
I found this one, which is rather old and pre-dates the work on the News designs. 

![image](https://user-images.githubusercontent.com/928100/80563607-ca258d80-89eb-11ea-8ce4-fdde87ce6d3d.png)

https://share.goabstract.com/42e46a84-0254-4043-9ffb-9db0b17b0278

As we have a [`vf-article-meta-information`](https://visual-framework.github.io/vf-core/components/detail/vf-article-meta-information.html), we should use it. Which is what you've done here.

**Comment by khawkins98** [comment]
There might be some follow on questions, like if it still makes sense to show "Latest posts" in the grey infobox, but that can be done later.

**Comment by sturobson** [comment]
> I went through Mark's designs in Abstract but didn't find anything. Here is a very basic layout with a sidebar:
> ![Screenshot 2020-04-29 at 07 23 23](https://user-images.githubusercontent.com/54020899/80563342-1ae8b680-89eb-11ea-8d7b-d98daedf574f.png)

does this match any of the existing grids being used?

**Comment by kasprzyk-sz** [comment]
It's `vf-inlay` with `main` and `additional` content

**Comment by sturobson** [comment]
Does that match the use case for `vf-inlay`? A website (group) within a website?

**Comment by kasprzyk-sz** [comment]
Every piece of content in `vf-wp-groups` theme is wrapped in `vf-inlay`. Singe blog post page just follows this grid.

**Comment by sturobson** [comment]
ok, so that's a yes :)

**Comment by sturobson** [comment]
the spacing between the to grid columns is a little tight. 

It's something I need to tidy up in `vf-core` too. Since the `vf-card` was introduced and sprinkled liberally on embl.org the gap was increased to 40px (still to be ratified and confirmed as it's not really 'of the system' as a value).
