### ISSUE TITLE
BUG - EMBL Publications query not working anymore?

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#248]
https://content.embl.org/api/v1/pattern.html?source=contenthub&pattern=embl-team-publications&limit=100&sort-field-value[changed]=DESC&title=Ellenberg

returns nothing

**Comment by meladawy** [comment]
Hey @khawkins98 this API endpoint is just a proxy to EDR website. When you query Ellenberg team, the ContentHub fetch the team ID of Ellenberg (42 in this case) and make another query to EDR to fetch the publications :- 

http://xs-bdr.embl.de/v2/publications/G-42

The publications of Ellenberg team in EDR database is empty.

**Comment by meladawy** [comment]
Do you think they have changed the API?

**Comment by khawkins98** [comment]
Hrm, sample ones from docs aren't working either, except for the CPID one:


```
- IDs for publications are in the format 'CF-XXX' for core facilities, 'G-XXX' for groups, 'CP-XXXXXXXX' for people. For example:

  - Publications for PepCore - http://xs-db.embl.de/v2/publications/CF-143
  - Publications for Hentze Group - http://xs-db.embl.de/v2/publications/G-37
  - Publications for Matthias Hentze - http://xs-db.embl.de/v2/publications/CP-60003181
```

https://gitlab.ebi.ac.uk/emblorg/backlog/

I'll ping IT

**Comment by khawkins98** [comment]
IT has now resolved this: https://wwwdev.embl.org/groups/dummy-embl-group/publications/
