### ISSUE TITLE
FEATURE - Add News block to Gutenberg editor

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#258]
We'd like to be able to insert a block for the latest EMBL news in the editor. These would come from the contentHub.

Desirable options:

- Limit/count: default 3
- Sort: date newest first
- Filters:
  - EMBL.org terms
    - https://www.embl.org/api/v1/pattern.html?pattern=vf-news-item-default&filter-content-type=article&filter-fields-exists=field_display_publication&sort-field-value%5Bcreated%5D=DESC&limit=3&filter-field-value[field_embl_taxonomy_terms.entity.uuid]=b7081c83-c191-4492-99e7-99145c27fa3e&source=contenthub
  - Free tags
    - Not yet supported (can we just add this option as not yet supported in contentHub?)
  - Keyword search
    - https://www.embl.org/api/v1/pattern.html?pattern=vf-news-item-default&filter-content-type=article&filter-fields-exists=field_display_publication&sort-field-value%5Bcreated%5D=DESC&limit=3&filter-all-fields=coronavirus&source=contenthub
  - Specific ID(s)
    - https://www.embl.org/api/v1/pattern.html?pattern=vf-news-item-default&filter-content-type=article&filter-fields-exists=field_display_publication&sort-field-value%5Bcreated%5D=DESC&limit=3&filter-id=27410,27376&source=contenthub

I think that's all the needed info?

**Comment by dbushell** [comment]
> Free tags: Not yet supported (can we just add this option as not yet supported in contentHub?)

Hey @khawkins98 can you clarify this part I'm not sure I understand.

**Comment by dbushell** [comment]
Are there any pattern/design variations for `vf-news-item-default`?

**Comment by dbushell** [comment]
Is it possible to search by multiple EMBL taxonomy terms, or just one?

**Comment by sturobson** [comment]
> Are there any pattern/design variations for vf-news-item-default?

What is that? `vf-summary--news` ?

**Comment by dbushell** [comment]
> > Are there any pattern/design variations for vf-news-item-default?
> 
> What is that? `vf-summary--news` ?

it's the pattern from the Content Hub API request – it does return `vf-summary--news`.

**Comment by khawkins98** [comment]
## Tags

> Free tags: Not yet supported (can we just add this option as not yet supported in contentHub?)

Can we have an option to query for "tags". These are the non-EMBL terms that are passed to th contentHub as uncontrolled terms. But we don't have a way yet to query for them. 

So while the user could add "`cheese`, `cancer`", we should note it won't actually do anything yet.... a placeholder. 

It's obviously not important that we have an input field here, more just a note that we plan to implement the functionality. 

## EMBL Terms

> Is it possible to search by multiple EMBL taxonomy terms, or just one?

Just one. 

Maybe in 3 or 4 months, we'll support `AND` `OR`, but the contentHub API isn't there yet, I think. 

## Patterns/variants

- The VF pattern is: https://visual-framework.github.io/vf-core/components/detail/vf-summary--news-has-image.html
- The contentHub pattern is `vf-news-item-default`, which uses the above
  - it's just the one variant*


* We may make this look from the EMBL.org homepage "official" at some point, which would need to be an option, but we're not there yet

![image](https://user-images.githubusercontent.com/928100/80967614-f17ac100-8e16-11ea-8f5d-6cc26afd2e66.png)

**Comment by dbushell** [comment]
I've implemented it with conditional fields. Do we want to (or can we) combine filters?

I suppose only EMBL Taxonomy + Keyword search would make sense if combined.

**No filter:**

<img width="280" alt="Screenshot 2020-05-04 at 15 47 46" src="https://user-images.githubusercontent.com/998922/80982300-ab276100-8e1a-11ea-9366-4f70728588f5.png">

**Filter by ID(s):**

<img width="280" alt="Screenshot 2020-05-04 at 15 48 47" src="https://user-images.githubusercontent.com/998922/80982339-b8445000-8e1a-11ea-91c9-e6b81ed492da.png">

**Comment by khawkins98** [comment]
Hrm, yeah, I think that's probably the best way of doing it. 👍

**Comment by khawkins98** [comment]
One comment: "Latest" could maybe be moved to a "Sort" selectbox:

- Sort:
  - none
  - latest
  - maybe more in the future (alphabetical, etc)

**Comment by dbushell** [comment]
wouldn't the default sort "none" be the latest (by date)?

Perhaps an enhancement in future would be to replace "Search by: Latest" to "Default" in that field. Then add a second field for "Sort by" with date / alphabetical etc.

Anyway, I've merge the initial version!

**Comment by khawkins98** [comment]
Yeah, might be? I guess it depends if the contentHub does something by default unless specified (term relevance perhaps).

But, yeah, more than enough for v1.0 I think 👍
