### ISSUE TITLE
Fix vf-embed Gutenberg block for new precompiled template

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#260]
The [`vf-embed`](https://visual-framework.github.io/vf-core/components/detail/vf-embed--default.html) component now has an `AspectRatio` and `maxWidth`.

The old Gutenberg block relied on `style` prop from an older template to allow custom ratios:

<img width="279" alt="vf-embed-settings" src="https://user-images.githubusercontent.com/998922/80698081-81dc9d00-8ac9-11ea-823a-cf3cbc36d815.png">

amongst other properties that need to be realigned.

**Comment by dbushell** [comment]
Waiting on update https://github.com/visual-framework/vf-core/issues/898

**Comment by khawkins98** [comment]
Changes approved, @sturobson is merging. I'll push to npm later today.

**Comment by dbushell** [comment]
Gutenberg block updated, just waiting on the new component styles before testing.

**Comment by khawkins98** [comment]
@dbushell Have pushed the new components to npm, just need to:

- `yarn run update-components`
- `gulp build`

And should be set on the updated css and precompiled NJK template.
