### ISSUE TITLE
REFACTOR - Update vf-wp cache to serve and then invalidate 

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#27]
The current implementation of page caching is slow. 

Here's what currently happens when the cache expires (`$max_age = 300`):

1. Stale items exists in cache
1. Page serve request
1. Cache is dumped if `$cached_age > $max_age`
1. Cache is refreshed (can take 10+ seconds)
1. Cache filled
1. Page served

Conceptual improvement:

1. Stale items exists in cache
1. Page serve request
1. If cached items exist, regardless of age, page served
1. Cache is dumped if `$cached_age > $max_age`
1. Cache is refreshed (can take 10+ seconds)
1. Cache filled

**Comment by dbushell** [comment]
With issue #36 I've recognised the need to:

* Allow varying `max_age` per cached item
* Avoid specific items updating automatically (perhaps with max_age `999...`)

Further ideas:

* Force a refresh when an editor saves a page with cached content
