### ISSUE TITLE
update social icons to match vf-core

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#270]
Now we have had design agreement - we should look to update the social icons where they are used for vf-wp 

reference site: https://visual-framework.github.io/vf-core/components/detail/vf-social-links.html

**Comment by dbushell** [comment]
I don't think we're showing any social icons on the Groups theme but it looks like News does so I'll assign @kasprzyk-sz

**Comment by kasprzyk-sz** [comment]
Added in #277 

![Screenshot 2020-05-06 at 12 21 38](https://user-images.githubusercontent.com/54020899/81166665-28c2ac80-8f94-11ea-80e8-0390d3bedad7.png)

![Screenshot 2020-05-06 at 12 22 03](https://user-images.githubusercontent.com/54020899/81166712-3bd57c80-8f94-11ea-87df-1f65bfe9acfe.png)

In the newsletter container, I think it would be nicer to have the icon transparent

**Comment by dbushell** [comment]
Merged PR from @kasprzyk-sz 

Ready to close unless any feedback on the transparent icons?

**Comment by sturobson** [comment]
these are the agreed designs for on white and on dark grey so I think we stick with them for now.

Looking good @kasprzyk-sz
