### ISSUE TITLE
If there is no data resources can we hide that block completely instead of showing empty space

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#281]
Some group sites don't have resources to display but "resources" is part of our default template so that sections shows white big gap. Check below screenshot.

https://wwwdev.ebi.ac.uk/about/teams/software-development-operations/

![Screenshot 2020-05-06 at 12 51 33](https://user-images.githubusercontent.com/1227241/81173878-a7b9e400-8f98-11ea-8e20-597698d13a6a.png)

**Comment by dbushell** [comment]
This is fixed in https://github.com/visual-framework/vf-wp/pull/285 (I plan to merge this week).
