### ISSUE TITLE
FEATURE - Support non-group pages

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#29]
As part of the generic page building effort (project?), we'll need to be able to build pages that don't look like groups sites; that is:

![image](https://user-images.githubusercontent.com/928100/62357155-c4f5e980-b512-11e9-9a58-a8d495198854.png)

Left: [embl-boilerplate-page](https://visual-framework.github.io/vf-core/components/detail/embl-boilerplate-page.html) Right: [embl-group-page](https://visual-framework.github.io/vf-core/components/detail/embl-group-page.html)

Currently all vf-wp sites are assumed to be like the right side, but we'll also need to do the left side. The main difference will be in (not) adding a couple of classes to `div.vf-body` and if a `.vf-header.vf-header--inlay` is shown.

So we could probably do this any of these ways (or others):

- Make the group look a child theme
- Add a per-page level option of "show as a group page"
- Add a theme level option of "is a group site"

---

ALSO, there could (perhaps) in time be a couple other options:

- Is an EMBL-EBI group
- We may need to support a difference in look/options between scientific groups and admin teams
- We may want also support [embl-subsite-page](https://visual-framework.github.io/vf-core/components/detail/embl-subsite-page.html)

☝️ But those are still _maybes_

**Comment by dbushell** [comment]
Once I've completed PR #74 it will add the `vf-wp-groups` theme leaving `vf-wp` as a base for extending. The parent theme alone might be enough for the boilterplate design, since a lot of functionality is done via the plugins.

**Comment by dbushell** [comment]
PR #74 is now merge.

The `vf-wp-groups` child theme handles all the Group site design/templates.

The parent `vf-wp` theme has templates similar to the EMBL boilerplate, although not necessarily intended to be used alone.

I plan to develop another child theme – maybe `vf-wp-boilerplate` – that has various customisable options and more templates.

**Comment by khawkins98** [comment]
As the main issue here is resolved, closing and opened a new issue #142
