### ISSUE TITLE
BUG - "EMBL Grid" block doesn't output classes on frontend

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#293]
Attempting to use the "EMBL Grid" Gutenberg block:

- Seems to work fine in the editor
- Classes seem missing on the theme render

https://wwwdev.embl.org/press/wp-admin/post.php?post=2&action=edit
![image](https://user-images.githubusercontent.com/928100/81793856-3505b700-950a-11ea-89bb-076e25ba0bc0.png)

https://wwwdev.embl.org/press/
![image](https://user-images.githubusercontent.com/928100/81793804-27503180-950a-11ea-9c54-ca006f7f97e2.png)

I don't _think_ this is a known issue

**Comment by dbushell** [comment]
Possibly because at some point the VF didn't require classes? The grid block hasn't been updated in a while. It worked last time I tested!

If it works in the admin it's because I had to write custom styles for the Gutenberg editor (where 1000 `<div>s` are unavoidable).

**Comment by khawkins98** [comment]
Ah, yes: embl-grid doesn't require classes. I think the issue is that the `embl-grid` is in a container too narrow to support embl-grid.

**Comment by khawkins98** [comment]
Yeah, that's it.

If you change the wrapping `embl-grid embl-grid--has-centered-content` to a simple `vf-grid` it works: 

![image](https://user-images.githubusercontent.com/928100/81796414-b27ef680-950d-11ea-96fe-f3d8d7d38f72.png)

But that obviously does _other things_.

We might need some sort of option to select a layout for the WP content area:

- `embl-grid embl-grid--has-centered-content`
- `no grid` (add your own wrapping VF Gutenberg block grids)

**Comment by dbushell** [comment]
Is the wrapper class change enough of a "fix" for now?

I'm not particularly familiar with the grid styles or how they're used.

Ideally where possible we'd keep layout out of the Gutenberg editor and use page templates.

There are theme-specific templates – for example, the Groups pages with sidebar — the editor content sits in the main column. The default theme page has a centered column.

And there are the custom/dynamic templates that are configured with containers.

Maybe for the custom templates the "Page Content" placeholder can be configured with grid options? That may get tricky if the child theme is already putting that content inside a grid.

**Comment by khawkins98** [comment]
It might be enough in the parent vf-wp theme (or we had a new child theme) that didn't confine page content inside of `embl-grid embl-grid--has-centered-content`. 

Something like, if we swapped:

https://github.com/visual-framework/vf-wp/blob/21a66703ee3313f326e09e0b73dd2c57e1c1a91d/wp-content/themes/vf-wp/index.php#L18-L34

For 

```php
<!--/embl-grid-->
<section class="vf-grid"> <!-- 1 column, full width -->
  <div>
  <?php
  while (have_posts()) {
    the_post();
    get_template_part('partials/vf-summary--article');
    if ( ! $vf_theme->is_last_post()) {
      echo '<hr class="vf-divider">';
    }
  }
  vf_pagination();
  ?>
  </div>
</section>
```

That would achieve the flexibility needed for "generic page building", but:

1. Maybe that should be `singular.php`?
2. I don't _think_ that would affect the child themes?
3. Maybe we should do that in a new `vf-wp-pagebuilder` child theme?

**Comment by khawkins98** [comment]
Yeah, that should probably reference `singular.php` but I think it gets the idea across.

**Comment by dbushell** [comment]
I think this would work in the parent theme `singular.php` as long as child themes are overriding this when needed (which they do).

I'm hesitant on a `vf-wp-pagebuilder` theme as it could risk introducing features that won't be accessible to other child themes. On the other hand, it could prove a useful testing ground where features can be promoted to `vf-wp`.

**Comment by khawkins98** [comment]
👍  Sounds good by me. 

If there's not a clear need for `vf-wp-pagebuilder`, makes sense to not add it.

**Comment by dbushell** [comment]
Hey Ken, I've had a look at the blocks again. There is a "VF Grid" block and a separate "EMBL Grid" block. The EMBL Grid has these options:
<img width="277" alt="embl-grid-block" src="https://user-images.githubusercontent.com/998922/81816186-8027c600-951a-11ea-8ed7-5b393bd4874a.png">

The two toggles do add the necessary classes. From what I understand this is working as it should?

Still - need to improve the containing template options.

**Comment by khawkins98** [comment]
Yeah, so on further inspection the gutenberg blocks for vf-grid and embl-grid seem fine. It's just the containing template is giving the embl-grid too little space.
