### ISSUE TITLE
BUG - EMBL Documents - date filtering leads to 404 page

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-wp#296]
Using the date filter in [EMBL Documents](https://www.embl.org/documents/) always leads to a 404 page.

Also, would it be possible to have the Date filter show only years, to avoid having an overgrown selection?

Thanks

**Comment by dbushell** [comment]
Thanks I'll investigate. We did have date URLs working at some point.

Yes only years is possible good idea.

**Comment by filipe-dias** [comment]
Perhaps this may be connected with the Date filtering issue, but using the pages navigation at the bottom also leads to a 404.

**Comment by kasprzyk-sz** [comment]
I let myself to take over. Fixed in #330.
