### ISSUE TITLE
FEATURE - Display VF-WP Release version in admin

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#300]
This is not super urgent but it will good to have display of current installed release version which will be easy to verify which code is used by particular site.

For e.g `VF-WP Version v1.0.0-beta.5` 

Display this information on settings page or somewhere easily visible. This should apply to all groups/non-groups sites which are using this framework.

Similar to how wordpress shows version in bottom of page.
<img width="826" alt="Screenshot 2020-05-15 at 15 30 26" src="https://user-images.githubusercontent.com/1227241/82062142-93c16100-96c1-11ea-9240-86e4d1abbd72.png">

**Comment by khawkins98** [comment]
Ties in with discussions on #269

**Comment by sandykadam** [comment]
Or what I can do is drop release version at the time of deployment something like this https://wwwdev.embl.org/news/build.txt

But I will have to update in 2 files one in composer.json to provide actual version and one in .gitlab_ci file

**Comment by khawkins98** [comment]
Another idea discussed with @dbushell was that the `vf-wp` parent theme could be tagged with the release.

So to see the "overall" release you would look at the `vf-wp` parent theme version: https://wwwdev.embl.org/news/wp-admin/themes.php?theme=vf-wp

![image](https://user-images.githubusercontent.com/928100/82072384-eefe4e00-96d7-11ea-8f2c-eb07458caa8b.png)

**Comment by dbushell** [comment]
I like the idea of the admin footer.

There are two WP filters:
 * [`admin_footer_text`](https://developer.wordpress.org/reference/hooks/admin_footer_text/) that can alter the "Thank you" text
* [`update_footer`](https://developer.wordpress.org/reference/hooks/update_footer/) which I think is the version

I'll append the parent theme version to whichever works.

**Comment by dbushell** [comment]
<img width="300" alt="Screenshot 2020-05-18 at 12 13 28" src="https://user-images.githubusercontent.com/998922/82207006-b2f60380-98f8-11ea-8e7e-b79bc2fa7369.png">

This will appear from `beta.7` onwards.

It uses the [`vf-wp`](https://github.com/visual-framework/vf-wp/blob/master/wp-content/themes/vf-wp/style.css#L6) theme version.

Naturally we're forgetting to update that on each release.

I suppose the main `vf-wp/index.php` plugin and `package.json` should also use the same version.

Any suggestions to automate that – some kind of Git hook or task?

**Comment by sandykadam** [comment]
v7 deployed on all group sites and its showing VF version in footer.
![Screenshot 2020-05-22 at 11 39 51](https://user-images.githubusercontent.com/1227241/82659744-19dd2a80-9c21-11ea-9b08-869702d67ab3.png)

**Comment by sandykadam** [comment]
Not sure if we going to create another issue for this as we still get beta.7 in footer and not the version we have deployed. Currently we have v25 deployed but we still have beta.7.
Again its not something urgent but kind of good to have.

**Comment by sandykadam** [comment]
Added new fix to show version in admin interface - https://github.com/visual-framework/vf-wp/pull/1026
