### ISSUE TITLE
global header is inside a header inside a header 

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#313]
```
<header class="vf-header">
  <div class="vf-content-hub-html" data-cache="f6ebcf25">
  <!-- Generated by: http://content.embl.org/api/v1/pattern.html?filter-content-type=article&amp;filter-id=574&amp;pattern=node-body -->
  
  <div data-embl-js-conditional-edit="574">
    <header class="vf-header">
      <div class="vf-global-header">
        <div class="vf-global-header__inner">
          <a href="/" class="embl-logo | embl-logo--responsive"></a>
          <nav class="vf-navigation vf-navigation--global">
            <ul class="vf-navigation__list | vf-list--inline">
              <li class="vf-navigation__item">
                <a href="https://www.embl.org/explore" class="vf-navigation__link">Explore</a>
              </li>
              <li class="vf-navigation__item">
                <a href="https://www.embl.org/search" class="vf-navigation__link">Search</a>
              </li>
         </ul>
      </nav>
    </div>
  </div>
</header>
            <a class="vf-text vf-text--body-r vf-link embl-conditional-edit" rel="noopener noreferrer nofollow" href="https://content.embl.org/node/574" target="_blank">Edit</a>
        </div>
    </div>
</header>
```

should be just the content-hub include now - no need for the first vf-header

**Comment by dbushell** [comment]
Hmm interesting the content hub template differs:
https://content.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=574&pattern=node-body

The dev version has no `vf-header` wrapper:
https://dev.content.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=574&pattern=node-body


Should I be using the `dev` URL @khawkins98 ?

**Comment by sturobson** [comment]
I think the output in `vf-wp` should be this –
```
<div class="vf-content-hub-html" data-cache="f6ebcf25">
  <!-- Generated by: http://content.embl.org/api/v1/pattern.html?filter-content-type=article&amp;filter-id=574&amp;pattern=node-body -->
  
  <div data-embl-js-conditional-edit="574">
    <header class="vf-header">
      <div class="vf-global-header">
        <div class="vf-global-header__inner">
          <a href="/" class="embl-logo | embl-logo--responsive"></a>
          <nav class="vf-navigation vf-navigation--global">
            <ul class="vf-navigation__list | vf-list--inline">
              <li class="vf-navigation__item">
                <a href="https://www.embl.org/explore" class="vf-navigation__link">Explore</a>
              </li>
              <li class="vf-navigation__item">
                <a href="https://www.embl.org/search" class="vf-navigation__link">Search</a>
              </li>
         </ul>
      </nav>
    </div>
  </div>
</header>
```

I'm assuming the first `vf-header` was from `vf-wp`?

**Comment by khawkins98** [comment]
Yeah, this is "content" and the dev version is older. 

In all cases we'll want to use the production URL unless we're testing something specific. And we should also use the cache: `https://www.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=574&pattern=node-body&source=contenthub`

**Comment by sturobson** [comment]
So, I think it's the first of the two David's linked to?

**Comment by dbushell** [comment]
The `https://www.embl.org/api/v1/` production URL doesn't work for me in the local Docker. Have yet to investigate but assuming an issue with the cache CURL request.

**Comment by khawkins98** [comment]
Does your query end in `&source=contenthub`?

**Comment by khawkins98** [comment]
> So, I think it's the first of the two David's linked to?

Yeah. The `dev.content` and `content.` aren't meant to be queried directly. I think the vf-wp header implementation predates circulation of "best working practice"

**Comment by dbushell** [comment]
> Does your query end in `&source=contenthub`?

yep – query is identical to the dev requests. It works when I access in my browser but somewhere in Docker it's failing.

**Comment by khawkins98** [comment]
Strange. 

But if you use `https://conent.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=574&pattern=node-body&source=contenthub` that works fine?

It's just `https://www.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=574&pattern=node-body&source=contenthub` that fails?

**Comment by dbushell** [comment]
Yeah `content` works too. I was using `dev.content`. The `www` fails.

**Comment by khawkins98** [comment]
Well, I'd say let's just use `content.` as that will at least resolve the issues @sturobson raised. 

Can make a new ticket about what's happening in Docker. Could need Sandeep's help.
