### ISSUE TITLE
BUG/CHORE - Advanced Custom Fields newer versions missing cache.php

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#32]
We're currently using `5.8.0-beta3`. 

Some time back I tried to update to `beta4` but that broke things as `cache.php` had been removed. 

I had started a ticket with the maintainer but have shamefully not followed up ... and it may have been resolved it the latest version (I'd try again, but I can't seem to find the user/pass for the pro version — but looking at the [release notes](https://www.advancedcustomfields.com/blog/) it doesn't seem like the cache has been added back).

My "report":

>With the beta.4 we noticed that `includes/cache.php` has been removed -- we were previously using functions like acf_disable_cache(). 
>
> If cache.php wasn't accidently removed, is it not recommended to use acf_disable_cache()?  

Response: 
 
> We made changes to our "cache" functions in version 5.7.11.
>
> These changes have been included in the latest 5.8.0 beta-4.
>
> Can you please provide some more info/context on why you were using those functions?Perhaps they are no longer needed? Or perhaps we need to add them back in.

Maybe David's already changed his approach or found a workaround.

**Comment by dbushell** [comment]
I think I've found a fix for latest ACF (5.8.4).

It seems the cache stuff isn't intended for public use. It's certainly not documented.

Going foward I plan to refactor using native Gutenberg blocks to avoid this issue recurring (and make #28, #29 easier to implement). How I'm using ACF here is a bit of a hack anyway.

Pull request to come...
