### ISSUE TITLE
Local dev setup scripts and config

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#33]
The scripts `bin/dev quick_group` etc are failing to configure WordPress.

I was seeing a lot of errors:

```
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
``` 
It would eventually load a default unconfigured WordPress in the browser on the install page.

I had to add this to my `.env` file:

```
WP_SETTINGS_PHP=${RELATIVE_DOCUMENT_ROOT}/wp-config.php
WP_DEFAULT_SETTINGS_PHP=${RELATIVE_DOCUMENT_ROOT}/wp-config-sample.php
```

and then the setup process was able to bootstrap successfully.

Not sure if this the permanent solution I should commit?

**Comment by khawkins98** [comment]
This looks right by me, but you might double check @sandykadam ?

**Comment by sandykadam** [comment]
It should be correct, try again sometimes containers doesn't spin up so it is unable to connect to DB.

**Comment by sandykadam** [comment]
I just checked, its working fine. Sometimes containers & mysql service is not started so setup doesn't connect to DB. You will have try again by doing.
`bin/dev down` & `bin/dev quick_group` or `bin/dev quick_group_bootstrap` with full site bootstrap version.
