### ISSUE TITLE
EHNAHCEMNT - Add time zone to event fileds

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#335]
Related to the now-mostly-done #228 (Events plugin stage 2 requirements) we also need support for time zones on event fields.

We could do this in a couple of ways:

1. One time zone for an entire vf-events post 
   - "All times on this event are GMT"
2. A time zone for each option
   - "Abstract submission deadline is GMT, event time is CET"

Option 1 is probably the most user (and developer?) friendly — I have a hard time thinking we _have_ to have scenario 2. 

Priority high as it's required for Liang's work to progress.

**Comment by shenzhuxi** [comment]
This field should provide validated time zones https://www.php.net/manual/en/timezones.php. "America/New York" is not.

**Comment by kasprzyk-sz** [comment]
Corrected in [9bd5755c](https://github.com/visual-framework/vf-wp/commit/9bd5755cd01150389ab15f55432f22dcd3340405)
