### ISSUE TITLE
ENHANCEMENT - Event link field should be a full URL

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#343]
If possible we should require a fully-qualified link

- 🚫  `../link`
- 🚫  `link`
- ✅  `https://example.com`
- ✅  `http://example.com`

**Comment by kasprzyk-sz** [comment]
ACF field validation is not working anymore.

![Screenshot 2020-06-04 at 11 21 47](https://user-images.githubusercontent.com/54020899/83739410-d7224600-a655-11ea-9c10-5da03ed2ac65.png)

I'm not sure if there is other solution, so I'm leaving this to David.

In the meantime, we could add instructions/placeholder text to enter the full URL

**Comment by kasprzyk-sz** [comment]
With the latest update of ACF, the url field requires now a fully-qualified link
![Screenshot 2020-10-02 at 12 59 56](https://user-images.githubusercontent.com/54020899/94916561-316dcf00-04af-11eb-8865-2c5ba10c744e.png)
