### ISSUE TITLE
Update permissions to allow "group admins" to edit containers

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#405]
As discussed with @pwalter-ebi and @kasprzyk-sz, group admins will want to be able to edit the Group header container to change links, themes and add images.

This is a permissions issue, do we need your help @sandykadam to change these settings?

**Comment by kasprzyk-sz** [comment]
This is the info that you get after clicking on containers and being logged in as a Group Admin. 

![Screenshot 2020-08-18 at 14 01 16](https://user-images.githubusercontent.com/54020899/90510465-530f3300-e15b-11ea-8057-1714bd3fb661.png)

**Comment by sandykadam** [comment]
@khawkins98 Permission to access "Content Hub" > Container | Blocks is tightly coupled with "manage_option" capability which opens up all access to user.  Please check https://github.com/visual-framework/vf-wp/blob/master/wp-content/plugins/vf-wp/index.php#L223

I think it will open all administrator access to "group_admin" role user, once @dbushell is back we should check with him if there is way to make it more customised capabilities for this section rather wrapping it under core manage_option.

For now I will enable this so group_admins can have access.

**Comment by sandykadam** [comment]
Fix commit - https://github.com/visual-framework/vf-wp/commit/e145ea1ed8a6e067bc0aeb4c45f7426da2de7320

**Comment by khawkins98** [comment]
Thanks @sandykadam. Have assigned to David to review once he's back.
