### ISSUE TITLE
Preview uses the wrong template

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#406]
When previewing a page it uses the sidebar template, even though the full width is selected.

Published:

![image](https://user-images.githubusercontent.com/928100/88433572-a4e3c800-cdfe-11ea-8792-30e7db40b142.png)

Preview:

![image](https://user-images.githubusercontent.com/928100/88433595-ac0ad600-cdfe-11ea-9cd5-6ae06b49555b.png)

Editor:

![image](https://user-images.githubusercontent.com/928100/88433614-b4fba780-cdfe-11ea-9b69-bb290e856459.png)

**Comment by kasprzyk-sz** [comment]
This is fixed by creating a separate page template with sidebar.
![Screenshot 2020-08-03 at 08 27 12](https://user-images.githubusercontent.com/54020899/89152312-34a61680-d563-11ea-98d1-e9232c1910d9.png)
