### ISSUE TITLE
News container: additional customisation

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#473]
Would be good to have two additional options in the news containers for microsites:

### 1. Make "EMBL News" into a section header

Should be customisable and allow for a link + summary text.

So we could do something like. 

"[COVID-19 News](link-to-special-covid19-page)"
"Read more COVID-19 research news from EMBL"

### 2. Rich HTML area in addition to displaying a factoid 

For the right column, this would not be in a green box but a standard `vf-content` area for all the other misc needs

**Comment by kasprzyk-sz** [comment]
2. Suggested solution:

To register a sidebar for EMBL News container and add option to enable/disable it in the container settings. This will allow to add all the components that are available as widgets to the News sidebar.

 Widget settings:
![Screenshot 2020-09-04 at 11 39 06](https://user-images.githubusercontent.com/54020899/92225885-26218680-eea4-11ea-9177-c02dbac8fffa.png)
Output:
![Screenshot 2020-09-04 at 11 38 50](https://user-images.githubusercontent.com/54020899/92225911-2d489480-eea4-11ea-9696-64bffeba796c.png)

**Comment by khawkins98** [comment]
Nice, sounds good and flexible.
