### ISSUE TITLE
Anchor field value must be full URL

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-wp#528]
After ACF's update, pages with anchors not using a full URL prevent a page from being saved.

Example from: https://www.embl.org/news/lab-matters/alpx/

![anchor](https://user-images.githubusercontent.com/46531832/95457796-4f34ab80-0969-11eb-81d9-a9d39952fd3d.png)

**Comment by kasprzyk-sz** [comment]
I replaced the acf url field with the text field. The values have been saved so no need to update older articles.
