### ISSUE TITLE
ENHANCEMENT - add option to merge columns in vf-grid

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-wp#565]
It would be great if we could add a feature to the `vf-grid` block that allows merging columns by adding `vf-grid__col--span-X` class.

Example:
`vf-grid | vf-grid__col-3`

<img width="1391" alt="Screenshot 2020-11-02 at 11 09 38" src="https://user-images.githubusercontent.com/54020899/97856269-5cd91900-1cfc-11eb-9f1b-a413be7d7d39.png">

HTML
```
<div class="vf-grid | vf-grid__col-3">
   <div></div>
   <div></div>
   <div></div>
</div>
```

`vf-grid | vf-grid__col-3` with `vf-grid__col--span-2`

<img width="1356" alt="Screenshot 2020-11-02 at 11 11 38" src="https://user-images.githubusercontent.com/54020899/97856281-5fd40980-1cfc-11eb-8c06-5762333bcda1.png">

HTML
```
<div class="vf-grid | vf-grid__col-3">
   <div class="vf-grid__col--span-2"></div>
   <div></div>
</div>
```

**Comment by dbushell** [comment]
Thanks I'll get working on this. Made some progress in https://github.com/visual-framework/vf-wp/issues/28 but that's probably outdated. I'll close the issue there and work on it here.

**Comment by dbushell** [comment]
Progress here - working technically there are a few UX issues I'll fix up today. I've added some background colors and outlines for a visual aid – not sure how visible they are the EMBL UI colors are quite light.

<img width="989" alt="Screenshot 2020-11-05 at 09 43 13" src="https://user-images.githubusercontent.com/998922/98224450-64dac800-1f4b-11eb-8530-7c0ed9160498.png">
<img width="983" alt="Screenshot 2020-11-05 at 09 44 47" src="https://user-images.githubusercontent.com/998922/98224617-92c00c80-1f4b-11eb-801f-765c562cae6f.png">

**Comment by kasprzyk-sz** [comment]
Looks good. Great work @dbushell 👍

**Comment by sturobson** [comment]
This'll all be fine until I update those classnames, jk.
