### ISSUE TITLE
BUG - vf-hero and vf-masthead preview in the editor

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-wp#577]
`vf-hero` and `vf-masthead` background image is not rendered in the editor. 

Editor view:
![Screenshot 2020-11-09 at 09 47 37](https://user-images.githubusercontent.com/54020899/98519374-fa8a9600-2270-11eb-8fdd-cc585557283f.png)

Preview:
![Screenshot 2020-11-09 at 09 47 45](https://user-images.githubusercontent.com/54020899/98519392-01b1a400-2271-11eb-8fc8-45676bf811ea.png)

**Comment by dbushell** [comment]
I've done a big update to the previews so it works for all blocks / containers.

However there is still an issue with the images – sometimes it works, othertimes not! I'm not sure but it's related to the ACF fields. I'll need to look into that further.

**Comment by dbushell** [comment]
I've noticed `--vf-masthead__bg-image: unset;` inline CSS is being added by some VF JavaScript which is removing an image I set. Perhaps the PHP templates need updating to match vf-core?

**Comment by kasprzyk-sz** [comment]
@dbushell To match the text colour, the image filename needs to have its most dominant colour added as a hexadecimal code. Otherwise, it won't be displayed. I think this is the issue here.

Example:
`masthead-background-image--00EF00.png`

Read more here:
https://stable.visual-framework.dev/components/vf-masthead/

**Comment by dbushell** [comment]
@kasprzyk-sz ah ok.

In that case I think this particular issue is resolved?

Maybe there needs to be some information for the editor to explain the filename?

Technically it might be possible to add a filter to append a default colour, but that might be more trouble than it's worth.

**Comment by sturobson** [comment]
Just a quick note that - you might want to work out how much effort this fix will be as `v3.0.0` will be amalgamating the two components -- https://codepen.io/sturobson/full/391b116416a7c12a880bb3c87852ded4 << that's not the finished article (well hero hah!) but it should show where things are going. 

- mortal kombat levels are going
- masthead and hero become hero
- some of the functionality might be 'hidden' for WP (tbd)
- the 'default' has lots of classes. 
- only admins should be able to change this
