### ISSUE TITLE
remove `vf-inlay` from components folder?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#590]
Whilst I dive into `master` looking for possible quick-wins of outdated component markup or CSS I noticed that this is still here: 

https://github.com/visual-framework/vf-wp/tree/master/vf-components/vf-inlay

As `vf-inlay` has been [deprecated](https://github.com/visual-framework/vf-core/pull/1204) in `vf-core` and I think you've started (finished?) deprecating it in `vf-wp` does it need removing entirely here?

**Comment by dbushell** [comment]
Yeh I think we can safely remove the package dependency from `vf-wp`.

The CSS get bundled in but I can't see any WordPress templates where it's used.

Not sure if anything from the Content Hub still uses it – had a quick look can't see it anywhere.

@kasprzyk-sz do you know if it's used anywhere?

**Comment by kasprzyk-sz** [comment]
I replaced the `vf-inlay` in all the WordPress templates, so it's good to go 👍

**Comment by sturobson** [comment]
Thanks @kasprzyk-sz + @dbushell
