### ISSUE TITLE
Enable home page editing for Group Admin role

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-wp#635]
The Group Admin role should have the rights to edit the home page. After a chat with @sandykadam -  when the project started, the pages like home, about, publications have been locked as they were supposed to be autogenerated. For the research groups, we are moving the 'about' content to the home page and some microsites will be build from scratch by the users so this capability is necessary.

**Comment by sandykadam** [comment]
Is it only for research groups or for all groups?

**Comment by kasprzyk-sz** [comment]
This was fixed quite some time ago. The Group Admin role has the capability to edit the home page.
