### ISSUE TITLE
Add Gutenberg transform for VF Grid and EMBL Grid blocks

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#64]
[Gutenberg block transforms](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#transforms-optional) provide a convenient way to convert blocks.

The `vf/grid` and `vf/embl-grid` both use similar inner blocks template with `vf/grid-column` as the only allowed children. Transforming between the two should be easy?

Consult the `setColumns` callback for merging columns.

**Comment by khawkins98** [comment]
One other thing for the `vf-grid` is spanning columns; in the format of `vf-grid__col--span-2`

**Comment by dbushell** [comment]
> One other thing for the `vf-grid` is spanning columns; in the format of `vf-grid__col--span-2`

Ah right - that could be tricky in the UI! are the classes document, I've been following:
https://visual-framework.github.io/vf-core/components/detail/vf-grid.html

**Comment by dbushell** [comment]
Basic grid support with transforms has been merged into master.

Column span work in progress: #68
