### ISSUE TITLE
bug: inline links in banners need to be wrapped in a class

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-wp#703]
Looking at [this page](https://www.embl.org/news/science/sars-cov-2-b117/) I've noticed that the links in the `vf-banner` are blue, where as they should be the same colour as the text. 

This is because these links do not have the required classname added - `vf-banner__link`.

Documentation [page](https://stable.visual-framework.dev/components/vf-banner/) for reference.

**Comment by kasprzyk-sz** [comment]
This is fixed with https://github.com/visual-framework/vf-wp/commit/428cafd818d54658ab70436d9c51973156b054f8
