### ISSUE TITLE
Enhancement: update default containers to have navigation

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#743]
In https://gitlab.ebi.ac.uk/emblorg/backlog/-/issues/467 we agreed to change the default navigation, however (discussing with @sandykadam) we should also add the vf-navigation container to the `default_template`  and `front_page_template` in vf-wp:

https://github.com/visual-framework/vf-wp/blob/ea61be40cd907de2011e65e8b1c4262ada1aba3a/wp-content/plugins/vf-wp/vf-templates.php#L48-L87

It should follow `<!-- wp:acf/vf-container-wp-groups-header {"id":"' . uniqid('block_') . '","name":"acf/vf-container-wp-groups-header"} /-->`

**Comment by khawkins98** [comment]
Also @kasprzyk-sz it will simplify @sandykadam 's deployment script if we can also add the EBI header and footer to the `default_template` and `front_page_template` functions. 

Then a page will get either the EBI or EMBL header depending on which plugin is activated (or, both headers, if both plugins are active 😄 )

**Comment by khawkins98** [comment]
Hey @kasprzyk-sz  the ebi header and footer template code added in #812 has been reverted. Was that intentional?

https://github.com/visual-framework/vf-wp/commit/5c3ec2a61da4e17643b262af0cd0a885c2d71b3f

**Comment by kasprzyk-sz** [comment]
There was an issue with creating new templates. Re-added in #819

**Comment by kasprzyk-sz** [comment]
The EBI templates has been added. The navigation issue is related to the #821 (resolved)
