### ISSUE TITLE
Update screenshots & description for available themes

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#804]
Currently it is difficult to understand which theme to use and how does it look like in "Appearance > Themes" admin console. So it will be good if we can add some actual screenshots and update more details of the theme like when should we use and for which types of websites.

![Screenshot 2021-05-18 at 10 31 32](https://user-images.githubusercontent.com/1227241/118628578-a2ef5900-b7c4-11eb-9775-0e3b00c86617.png)

**Comment by kasprzyk-sz** [comment]
This has been resolved in 1915abfe2392fa38bf2b14623ab335d6a75085e0

![Screenshot 2021-06-08 at 07 43 16](https://user-images.githubusercontent.com/54020899/121129450-41536500-c82d-11eb-8e84-a9f56cf4e5ee.png)
