### ISSUE TITLE
Placeholder ticket - Add toggle option to indicate if news is for EBI

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#817]
As part of EBI website migration to static pages, we need to migrate EBI news to embl.org/news website. Both EMBL & EBI news will be added in same system, so to differentiate them we need a field to indicate if its EBI news. This also needs to sync in ContentHub.

![Screenshot 2021-05-26 at 15 55 36](https://user-images.githubusercontent.com/1227241/119683111-4e3e8480-be3b-11eb-9238-3c1ca9aea2ab.png)

**Comment by kasprzyk-sz** [comment]
This is done with https://github.com/visual-framework/vf-wp/commit/8ee77cd9fdae341b4a1c2828943fbde55b1c1bdb
