### ISSUE TITLE
Menus doesn't show up if we setup website without taxonomies

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#821]
Recently we are setting up group sites without any taxonomies, same for EBI we only add Home & members menu by default. But when we view the website it only shows header/footer without menus.

**Comment by kasprzyk-sz** [comment]
The navigation menu is a part of a Groups Header container. It appears once it is updated. 

There is an option to switch on/off the navigation inside the Groups Header but in fact, it's not needed anymore. I'm going to remove it and hard code it as a part of the template. That should solve this issue.
