### ISSUE TITLE
Support default Gutenberg alignment (for image and other blocks)

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#85]
Image blocks (and others) have the default alignment attribute:
<img width="283" alt="gutenberg-image-alignment" src="https://user-images.githubusercontent.com/998922/68664979-262d5000-0539-11ea-8301-7e6f0a0b06df.png">

Right now this is ignored by the `vf-gutenberg` plugin which re-writes the markup here:
[`vf-gutenberg/includes/core/core-image.php`](https://github.com/visual-framework/vf-wp/blob/master/wp-content/plugins/vf-gutenberg/includes/core/core-image.php)

We should either remove the align options if unsupported using [block filters](https://developer.wordpress.org/block-editor/developers/filters/block-filters/) to alter the `supports` attribute. Or update the new markup to account for this option.

See [Utility Classes: Float](https://visual-framework.github.io/vf-core/components/detail/vf-utility-classes--float.html) in `vf-core`.

Todo: list all default WP blocks that include `align` support.

**Comment by khawkins98** [comment]
Setting as high as this is a frequent ask from users.

**Comment by khawkins98** [comment]
We made some progress on this one in #197, but we should see if it does everything we need it to. 

And we should see if we can/should push along https://github.com/visual-framework/vf-core/issues/813

**Comment by dbushell** [comment]
I may need to remove the `<div class="wp-block-image">` wrapper – working on some changes in this area beforehand.

**Comment by dbushell** [comment]
Other than images, do we have a list of blocks that should support alignment, either component specific, or generic utility classes?

**Comment by khawkins98** [comment]
I don't think we have much yet, but I suspect we'll have requests.... vf-box (factoid) to float right and such. 

Might be just something to be mindful of.

No other vf block support floating alignment, right @sturobson?

**Comment by khawkins98** [comment]
New alignment floats are in at https://github.com/visual-framework/vf-wp/blob/master/wp-content/themes/vf-wp/assets/css/styles.css#L141-L145

- https://visual-framework.github.io/vf-core/components/detail/vf-figure.html
- https://visual-framework.github.io/vf-core/components/detail/vf-content.html

**Comment by dbushell** [comment]
I've updated the `start` `end` classes. Is there code for "Align center"? @sturobson

**Comment by dbushell** [comment]
This is what WordPress looks like for "Align center" assuming the image is smaller than the parent wrapper.

<img width="814" alt="Screenshot 2020-05-04 at 10 44 58" src="https://user-images.githubusercontent.com/998922/80953921-f413f100-8deb-11ea-9e9f-ad81496db334.png">

**Comment by dbushell** [comment]
Almost there but it could use some margins.

Any suggestions @sturobson ?

<img width="794" alt="vf-figure--align" src="https://user-images.githubusercontent.com/998922/81050835-3c94e280-8eb0-11ea-9aef-32ce1dd54b87.png">

**Comment by sturobson** [comment]
missed the naming change to `align-` when the component is inside `vf-content`

Here's a PR - https://github.com/visual-framework/vf-core/pull/908
