### ISSUE TITLE
Old cache issues and options

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-wp#975]
### The issue
While there's a refresh rate for the WP caching, most microsites ignore this and end up having weeks/months old caches. 

There is only one [website](https://www.embl.org/groups/chemical-biology/) that I know is following the cache's assigned refresh rate (5 min), why is that and why others don't, I do not know.

### Impact
These old cache items impact on several aspects of the website, being the most noticeable and reported by the content owners is on changes to a person profile, mainly a photo that is not updated or set as publicly visible.

As the cache is the problem, what has been done is to go to the site and to clear the cache manually. Naturally, this is not something that is sustainable as we have over a hundred microsites and the action of clearing has to be repeated.

### Solutions
@sandykadam has proposed the possibility to try to find a fix for the code in place for the cache's refresh rate, or implement a script that could do this action at some time interval.

#### Related issues
https://gitlab.ebi.ac.uk/emblorg/backlog/-/issues/576#note_131946
https://github.com/visual-framework/vf-wp/blob/master/wp-content/plugins/vf-wp/vf-cache.php#L13
https://github.com/visual-framework/vf-wp/blob/master/wp-content/plugins/vf-wp/vf-cache.php#L336

**Update**
[Zimmermann](https://www.embl.org/groups/zimmermann) was one website where I cleared the cache today and is also following the refresh rate, wasn't before.

**Comment by sandykadam** [comment]
THis is fixed by https://github.com/visual-framework/vf-wp/pull/1177
