### ISSUE TITLE
vf-content is not added to inner blocks (grid, groups, etc)

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#98]
Paragraphs, headings, and lists need to be wrapped in a `vf-content` class.

**Comment by dbushell** [comment]
It may be easier to just wrap the entire post content in one `vf-content` element assuming `vf-core` CSS allows it. This could present its own problem with the `vf/grid` blocks which may need to break out the parent wrapper.

**Comment by sturobson** [comment]
This is what I would hope `vf-content` does … wrap around a 'blogpost' and style things nicely. 

I guess this can be complicated with the ability to add 'WP blocks' into the blogpost.  

Essentially - don't really want to have WP want to wrap every element in a post w/ `vf-content`
